url_fetch: "http://127.0.0.1:8000/measurements/all"
url_predict: "http://127.0.0.1:8000/measurements/predict"

#url_fetch: "http://141.45.212.246:8000/measurements/all"
#url_predict: "http://141.45.212.246:8000/measurements/predict"

num_measurements: -1
rooms: ["WH_C_351", "WH_C_352", "WH_C_353", "WH_C_335"]
corridors: ["WH_C_35_corridor"]

parameter_sets:
#  - name: "fastAPI"
#    parameters:
#      router_selection: ['all']
#      handle_missing_values_strategy: ['-100']
#      router_presence_threshold: [0]
#      router_rssi_threshold: [-100]
#      value_scaling_strategy: ['none']
#      algorithm:
#        random_forest:
#          n_estimators: [50]
#          max_depth: [9]
#          max_features: ['sqrt', 'log2', 'None', 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#  - name: "best_parameters_svm"
#    parameters:
#      router_selection: ['all']
#      handle_missing_values_strategy: ['-100']
#      router_presence_threshold: [0]
#      router_rssi_threshold: [-100]
#      value_scaling_strategy: ['none']
#      gamma_value: [1]
#      algorithm:
#        svm_rbf:
#          c_value: [0.001, 0.01, 0.1, 1, 10, 100, 1000]
#          gamma_value: ['scale', 'auto']
#  - name: "best_parameters_rf_2"
#    parameters:
#      router_selection: ['all']
#      handle_missing_values_strategy: ['-100']
#      router_presence_threshold: [0]
#      router_rssi_threshold: [-100]
#      value_scaling_strategy: ['none']
#      max_depth: [9]
#      algorithm:
#        random_forest:
#          n_estimators: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]


#  - name: "handle_missing_values_strategy"
#    parameters:
#      router_selection: ['all']
#      handle_missing_values_strategy: ['zero', '-100', 'use_received']
#      router_presence_threshold: [0]
#      value_scaling_strategy: ['none']
#      n_estimators: [ 50 ]
#      max_depth: [9]
#      algorithm:
##        knn_euclidean:
##          k_value: [5, 7, 9]
##        knn_sorensen:
##          k_value: [5, 7, 9]
#        random_forest:
#          max_features: [0.8, 2, 8]
##        svm_linear:
##          c_value: [0.001, 0.005, 0.01]
##        svm_rbf:
##          c_value: [ 5.0, 1.0, 0.5 ]


#  - name: "router_selection"
#    parameters:
#      router_selection: ['all', 'eduroam']
#      handle_missing_values_strategy: ['-100']
#      router_presence_threshold: [0]
#      value_scaling_strategy: ['none']
#      n_estimators: [ 50 ]
#      max_depth: [9]
#      algorithm:
##        knn_euclidean:
##          k_value: [5, 7, 9]
##        knn_sorensen:
##          k_value: [5, 7, 9]
#        random_forest:
#          max_features: [0.8, 2, 8]
##        svm_linear:
##          c_value: [0.001, 0.005, 0.01]
##        svm_rbf:
##          c_value: [ 5.0, 1.0, 0.5 ]


#  - name: "router_presence_threshold"
#    parameters:
#      router_selection: ['eduroam']
#      handle_missing_values_strategy: ['-100']
#      router_presence_threshold: [0, 0.25, 0.5, 0.75]
#      value_scaling_strategy: ['none']
#      n_estimators: [ 50 ]
#      max_depth: [9]
#      algorithm:
##        knn_euclidean:
##          k_value: [5, 7, 9]
##        knn_sorensen:
##          k_value: [5, 7, 9]
#        random_forest:
#          max_features: [0.8, 2, 8]
##        svm_linear:
##          c_value: [0.001, 0.005, 0.01]
##        svm_rbf:
##          c_value: [ 5.0, 1.0, 0.5 ]

#  - name: "router_rssi_threshold"
#    parameters:
#      router_selection: ['eduroam']
#      handle_missing_values_strategy: ['-100']
#      router_presence_threshold: [0]
#      router_rssi_threshold: [-100, -90, -80, -70, -60, -50, -40]
#      value_scaling_strategy: ['none']
#      n_estimators: [ 50 ]
#      max_depth: [9]
#      algorithm:
##        knn_euclidean:
##          k_value: [5, 7, 9]
##        knn_sorensen:
##          k_value: [5, 7, 9]
#        random_forest:
#          max_features: [0.8, 2, 8]
##        svm_linear:
##          c_value: [0.001, 0.005, 0.01]
##        svm_rbf:
##          c_value: [ 5.0, 1.0, 0.5 ]

#  - name: "value_scaling_strategy"
#    parameters:
#      router_selection: ['eduroam']
#      handle_missing_values_strategy: ['-100']
#      router_rssi_threshold: [-100]
#      value_scaling_strategy: ['none', 'exponential', 'powed', 'positive']
#      weights: ["distance"]
#      n_estimators: [ 50 ]
#      max_depth: [9]
#      algorithm:
##        knn_euclidean:
##          k_value: [5, 7, 9]
##        knn_sorensen:
##          k_value: [5, 7, 9]
#        random_forest:
#          max_features: [0.8, 2, 8]
##        svm_linear:
##          c_value: [0.001, 0.005, 0.01]
##        svm_rbf:
##          c_value: [ 5.0, 1.0, 0.5 ]


  - name: "test_corrdior"
    parameters:
      router_selection: ['eduroam']
      handle_missing_values_strategy: ['-100']
      router_presence_threshold: [0]
      router_rssi_threshold: [-100]
      value_scaling_strategy: ['none']
      measurements_per_room: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
      measurements_per_corridor: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
      weights: ["distance"]
      algorithm:
        knn_euclidean:
          k_value: [5]



#  - name: "test"
#    parameters:
#      router_selection: ['all']
#      handle_missing_values_strategy: ['-100']
#      router_presence_threshold: [0]
#      router_rssi_threshold: [-100]
#      value_scaling_strategy: ['none']
#      weights: ["distance"]
#      algorithm:
#        knn_euclidean:
#          k_value: [7]
